version: '3.3'

services:

  swagger-ui:
    build: ./docker/openapi/swagger-ui
    image: swagger-ui:ui-0.0.1
    ports:
      - "8002:8080"
    volumes:
      - ./docs/openapi/:/openapi/
    environment:
      SWAGGER_JSON: /openapi/dist/v1/openapi.json

  swagger-merger:
    build: ./docker/openapi/swagger-merger
    image: swagger-merger:merger-0.0.4
    volumes:
      - ./:/project
    working_dir: /project
    command: >
     sh -c '
      watch "swagger-merger -c -i ./docs/openapi/src/v1/openapi.yml -o ./docs/openapi/dist/v1/openapi.json" ./docs/openapi/src/v1 &
      sh ./docker/openapi/swagger-merger/generateJsonSchema.sh ./docs/openapi/src/v1
     '

  # swagger-editor:
  #   image: swaggerapi/swagger-editor
  #   container_name: "swagger-editor"
  #   ports:
  #     - "8001:8080"
  #   volumes:
  #     - ./docs/openapi/resources/:/usr/share/nginx/html/openapi/
  #   environment:
  #     SWAGGER_FILE: /usr/share/nginx/html/openapi/openapi.yml

  # swagger-api:
  #   image: stoplight/prism:3
  #   container_name: "swagger-api"
  #   ports:
  #     - "8003:4010"
  #   command: mock -h 0.0.0.0 /openapi.yaml
  #   volumes:
  #     - ./stacks/function-stack/config/openapi.yml:/openapi.yaml