export:
  Resources:
    #=====================================#
    ## お問い合わせ履歴テーブル作成
    #=====================================#
    ContactHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodb.tableNames.CONTACT_HISTORY_DB_NAME}
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Tags:
          - Key: Name
            Value: ${self:custom.dynamodb.tableNames.CONTACT_HISTORY_DB_NAME}
          - Key: Project
            Value: ${self:custom.project}
          - Key: App
            Value: ${self:app}
          - Key: STAGE
            Value: ${self:provider.stage}

    #=====================================#
    ## 曲カテゴリー一覧格納用テーブル
    #=====================================#
    SongCategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodb.tableNames.SONG_CATEGORY_DB_NAME}
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 4
          WriteCapacityUnits: 4
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        Tags:
          - Key: Name
            Value: ${self:custom.dynamodb.tableNames.SONG_CATEGORY_DB_NAME}
          - Key: Project
            Value: ${self:custom.project}
          - Key: App
            Value: ${self:app}
          - Key: STAGE
            Value: ${self:provider.stage}

  #=== Outputs ===#
  Outputs:
    ## Dynamodb Table Arn
    ContactHistoryTableArn:
      Value: !GetAtt ContactHistoryTable.Arn
      Export:
        Name: ${self:provider.stackName}-ContactHistoryTableArn
    SongCategoryTableArn:
      Value: !GetAtt SongCategoryTable.Arn
      Export:
        Name: ${self:provider.stackName}-SongCategoryTableArn
    # Dynamodb Table Name
    ContactHistoryTableName:
      Value: !Ref ContactHistoryTable
      Export:
        Name: ${self:provider.stackName}-ContactHistoryTableName
    SongCategoryTableName:
      Value: !Ref SongCategoryTable
      Export:
        Name: ${self:provider.stackName}-SongCategoryTableName
