export:
  Resources:
    #=====================================#
    ## APIGateway kickRequestToMicroCMS関数実行権限付与
    #=====================================#
    KickRequestToMicroCMSApiPermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName: ${self:functions.kickRequestToMicroCMS.name}
        Action: "lambda:InvokeFunction"
        Principal: "apigateway.amazonaws.com"
      DependsOn: KickRequestToMicroCMSLambdaFunction

    #=====================================#
    ## APIGateway iframeConverter関数実行権限付与
    #=====================================#
    IframeConverterApiPermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName: ${self:functions.iframeConverter.name}
        Action: "lambda:InvokeFunction"
        Principal: "apigateway.amazonaws.com"
      DependsOn: IframeConverterLambdaFunction

    #=====================================#
    ## APIGateway 認証用関数の実行権限付与
    #=====================================#
    LambdaAuthorizerApiPermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName: ${self:functions.lambdaAuthorizer.name}
        Action: "lambda:InvokeFunction"
        Principal: "apigateway.amazonaws.com"
      DependsOn: LambdaAuthorizerLambdaFunction

    #=====================================#
    ## APIGateway 曲のカテゴリ操作関数の実行権限付与
    #=====================================#
    SongCategoriesApiPermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName: ${self:functions.songCategories.name}
        Action: "lambda:InvokeFunction"
        Principal: "apigateway.amazonaws.com"
      DependsOn: SongCategoriesLambdaFunction

    #=====================================#
    ## APIGateway CMS Webhook関数実行権限
    #=====================================#
    CmsWebhookApiPermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName: ${self:functions.cmsWebhook.name}
        Action: "lambda:InvokeFunction"
        Principal: "apigateway.amazonaws.com"
      DependsOn: CmsWebhookLambdaFunction

