openapi: "3.0.1"
info:
  description: "DANCHiサイト用のWebAPI"
  version: "1.0.0"
  title: ${self:custom.apigateway.name}
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: musics
x-amazon-apigateway-request-validators:
  basic:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true
  body-only:
    validateRequestBody: true
    validateRequestParameters: false


# servers:
#   - url: "https://9kch38y2h4.execute-api.ap-northeast-1.amazonaws.com/{basePath}"
#   variables:
#     basePath:
#       default: "/prd"
paths:
  /v1/musics:
    $ref: "./paths/v1/musics/index.yml"
  /v1/musics/detail/{id}:
    $ref: "./paths/v1/musics/detail_id.yml"
  /v1/musics/song-categories:
    $ref: "./paths/v1/musics/song-categories.yml"
  /v1/musics/utils/cms-webhook:
    $ref: "./paths/v1/musics/utils_cms-webhook.yml"
  /v1/musics/utils/iframe-converter:
    $ref: "./paths/v1/musics/utils_iframe-converter.yml"
  /v1/blogs:
    $ref: "./paths/v1/blogs/index.yml"
  /v1/blogs/detail/{id}:
    $ref: "./paths/v1/blogs/detail_id.yml"

components:
  ##
  ## schemas
  ##
  schemas:
    ## Requests
    MusicsCmsWebhookRequest:
      $ref: "./components/schemas/MusicsCmsWebhookRequest.json"
    MusicsSongCategories:
      $ref: "./components/schemas/MusicsSongCategories.json"
    ## Responses
    StandardResponse:
      $ref: "./components/schemas/StandardResponse.json" 
    BlogsResultList:
      $ref: "./components/schemas/BlogsResultList.json" 
    BlogsResult:
      $ref: "./components/schemas/BlogsResult.json" 
    MusicsResultList:
      $ref: "./components/schemas/MusicsResultList.json" 
    MusicsResult:
      $ref: "./components/schemas/MusicsResult.json" 
    ## Schema Model
    MusicsSchema:
      $ref: "./components/schemas/MusicsSchema.json" 
    BlogsSchema:
      $ref: "./components/schemas/BlogsSchema.json" 
    ## Queries
    MicroCMSQueries:
      $ref: "./components/schemas/MicroCMSQueries.json" 

  
  ##
  ## securytyShemes
  ##
  securitySchemes:
    apiKey:
      $ref: "./components/securitySchemes/apiKey.yml"
    lambdaAuthorizer:
      $ref: "./components/securitySchemes/lambdaAuthorizer.yml"