openapi: "3.0.1"
info:
  description: "DANCHiサイト用のWebAPI"
  version: "1.0.0"
  title: ${self:custom.apigateway.name}
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: musics
x-amazon-apigateway-request-validators:
  basic:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true
  body-only:
    validateRequestBody: true
    validateRequestParameters: false


# servers:
#   - url: "https://9kch38y2h4.execute-api.ap-northeast-1.amazonaws.com/{basePath}"
#   variables:
#     basePath:
#       default: "/prd"
paths:
  /v1/musics:
    $ref: "./paths/v1/musics/index.yml"
  /v1/musics/{id}:
    $ref: "./paths/v1/musics/index_id.yml"
  /v1/musics/iframe-converter:
    $ref: "./paths/v1/musics/index_iframe-converter.yml"
  /v1/blogs:
    $ref: "./paths/v1/blogs/index.yml"
  /v1/blogs/{id}:
    $ref: "./paths/v1/blogs/index_id.yml"

components:
  ##
  ## schemas
  ##
  schemas:
    ## Requests
    AuthRequestHeaders:
      $ref: "./components/schemas/AuthRequestHeaders.json" 
    IframeConverterRequest:
      $ref: "./components/schemas/IframeConverterRequest.json" 
    ## Responses
    StandardResponse:
      $ref: "./components/schemas/StandardResponse.json" 
    BlogsListResponse:
      $ref: "./components/schemas/BlogsListResponse.json" 
    BlogsObjectResponse:
      $ref: "./components/schemas/BlogsObjectResponse.json" 
    MusicsListResponse:
      $ref: "./components/schemas/MusicsListResponse.json" 
    MusicsObjectResponse:
      $ref: "./components/schemas/MusicsObjectResponse.json" 
    ## Schema Model
    MusicsSchema:
      $ref: "./components/schemas/MusicsSchema.json" 
    BlogsSchema:
      $ref: "./components/schemas/BlogsSchema.json" 
    ## Queries
    MicroCMSQueries:
      $ref: "./components/schemas/MicroCMSQueries.json" 

  
  ##
  ## securytyShemes
  ##
  securitySchemes:
    apiKey:
      $ref: "./components/securitySchemes/apiKey.yml"
    lambdaAuthorizer:
      $ref: "./components/securitySchemes/lambdaAuthorizer.yml"