export:
  handler: src/handlers/musics/IframeConverter.main
  package:
    include:
      - IframeConverter.js
  role: !ImportValue ${self:custom.stacks.common-stack.name}-IframeConverterLambdaRoleArn
  environment:
    ALLOW_ORIGIN: ${file(${self:custom.paths.envFile}):export.ALLOW_ORIGIN}
    SEND_ERROR_NOTICE_SNS_TOPIC_ARN: !ImportValue ${self:custom.stacks.common-stack.name}-SendErrorNoticeToEmailSNSTopicArn
  name: ${self:custom.servicePrefix.Lambda}-iframeConverter
  layers:
    - !Ref CommonLayerLambdaLayer
  tags:
    Project: ${self:custom.project}
    Name: ${self:functions.iframeConverter.name}
    App: ${self:app}
  memorySize: 512