export:
  handler: src/handlers/common/KickRequestToMicroCMS.main
  package:
    include:
      - KickRequestToMicroCMS.js
  role: !ImportValue ${self:custom.stacks.common-stack.name}-StandardLambdaRoleArn
  environment:
    ALLOW_ORIGIN: ${file(${self:custom.paths.envFile}):export.ALLOW_ORIGIN}
    SEND_ERROR_NOTICE_SNS_TOPIC_ARN: !ImportValue ${self:custom.stacks.common-stack.name}-SendErrorNoticeToEmailSNSTopicArn
    MICROCMS_API_BASEURL: ${file(${self:custom.paths.envFile}):export.MICROCMS_API_BASEURL}
    MICROCMS_API_KEY: ${file(${self:custom.paths.envFile}):export.MICROCMS_API_KEY}
  name: ${self:custom.servicePrefix.Lambda}-kickRequestToMicroCMS
  layers:
    - !Ref CommonLayerLambdaLayer
  tags:
    Project: ${self:custom.project}
    Name: ${self:functions.kickRequestToMicroCMS.name}
    App: ${self:app}
  memorySize: 1024